# Generated by Django 4.2 on 2023-04-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_prodeuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodeuct',
            new_name='Product',
        ),
    ]
