# Generated by Django 4.2 on 2023-04-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contacti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactI',
        ),
    ]
